# -*- coding: utf-8 -*-
"""Latihan if,elif,else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YAXUo8ACAy4ZWrM3JRFjUrq-bAck0-yT
"""

if True:
  print('Kode program ini akan dieksekusi')

if False:
  print('Kode program ini tidak akan dieksekusi')
print('Kode program ini akan selalu dieksekusi karena tidak termasuk percobaan')

nilai = 70.5
print('Nilai anda adalah:', nilai, '\n')
if nilai >= 70:
  print('Selamat, anda lulus!')
else:
  print('Maaf, anda tidak lulus.')

nilai = int(input('Masukan nilai anda:'))
print('Nilai anda adalah:', nilai, '\n')
if nilai >= 70:
  print('Selamat, anda lulus!')
else:
  print('Maaf, anda tidak lulus.')

nilai = int(input('Masukan nilai anda:'))

if nilai >= 90:
  print('Predikat A')
if nilai >= 90:
  print('Predikat A')
elif nilai >= 80:
  print('Predikat B')
elif nilai >= 60:
  print('Predikat C')
elif nilai >= 40:
  print('Predikat D')
else:
  print('Predikat E')

uah_yabuah_yang_tersedia = ['Jeruk', 'Mangga', 'Nanas', 'Apel']
bng_dicari = input('Masukan nama buah dalam huruf kapital: ')
if (buah_yang_dicari in buah_yang_tersedia):
  print('Buah yang anda cari tersedia!')
else:
  print('Buah yang anda cari tidak tersedia!')

nilai = int(input('Masukan nilai anda:'))
usia = int(input('Masukan nilai anda:'))
if nilai >= 70:
  if nilai < 15:
    print('Selamat adek, kamu lulus!')
  else:
    print('Selamat kakak, kamu lulus!')
else:
  if (usia < 15):
    print('Nice try, ya dek!')
  else:
    print('Nice try, bro!' )

