# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNg__-VNx4cRH9MAKCDlgSowQUBO77Tv
"""

>>> 10 + 5

>>> 10 - 50

>>> 10 ** 5

>>> 10 / 5

>>> 10 // 5

>>> 10 % 5

>>> 100 % 5

>>> 70 / 2

a, b = 7, 2

print(a, '+', b, '=', a + b)
print(a, '-', b, '=', a - b)
print(a, '*', b, '=', a * b)
print(a, '/', b, '=', a / b)
print(a, '%', b, '=', a % b)
print(a, '**', b, '=', a ** b)
print(a, '//', b, '=', a // b)

7 > 7

5 == 5

8 <= 7

8 <= 9

7 != 5

x, y = 30, 19

print(x, '+', y, '=', x + y)
print(y, '-', x, '=', y - x)
print(x, '*', y, '=', x * y)
print(y, '/', x, '=', y / x)
print(x, '%', y, '=', x % y)
print(y, '**', x, '=', y ** x)
print(x, '//', y, '=', x // y)

print(x, '>', y, '=', x > y)
print(y, '<', x, '=', y < x)
print(x, '==', y, '=', x == y)
print(y, '!=', x, '=', y != x)
print(y, '>=', x, '=', y >= x)
print(x, '<=', y, '=', x <= y)

x, y, c, d = 3, 4, 5, -5

print(y, '+', c, '*', x, '=', y + c * x)

print(y, '+', c, '*', x, '=', y + c * x)
print(y, '-', d, '**', x, '=', y + d ** x)
print(d, '//', y, '*', x, '=', d // c * x)

print(y, '>', c, '>', x, '=', y > c > x)

a = 10
print('a = 10 -> ', a)

a = int(a)

a /= 9
print('a /= 9 -> ', a)

print(True and True)

print(2 * 8 == 1 and True)

print(False or 5 > 1)

provinsi = 'Sumatra'
list_daerah = ['Aceh', 'Riau', 'Padang', 'Bangka belitung']

mahasiswa = {
    'Nama': 'Sinta',
    'Asal': 'Bangka'
}

print("Apakah 'm' ada si variabel provinsi?", 'm' in provinsi)
print("Apakah 'c' ada si variabel provinsi?", 'm' not in provinsi)
print("Apakah atribut 'nama' ada di variabel mahasiswa?", 'nama' in mahasiswa)

x = 3
y = 3
nama_x = 'fia'
nama_y = 'yanto'

print('x is y:', x is y)
print('nama_x is nama_y:', nama_x is nama_y)

#operator identitas

>>> id('hijau')
1356432890011
>>> id('hijau')
1356432890011
>>>

>>> id('10')
1356432890011